version: '3.3'

services:
  server:
    depends_on:
      - mongodb
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    working_dir: /app
  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=adminpassword
      - MONGODB_APPLICATION_DATABASE=eth_lend_bot
      - MONGODB_APPLICATION_USER=username
      - MONGODB_APPLICATION_PASS=password
    ports:
      - "27017:27017"