version: '3.3'

services:
  server:
    image: node:9.6.1
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=adminpassword
      - MONGODB_APPLICATION_DATABASE=chat
      - MONGODB_APPLICATION_USER=username
      - MONGODB_APPLICATION_PASS=password
    tty: true